default_platform(:ios)

platform :ios do

  desc "Run unit tests"

  lane :tests do
    scan(
      scheme: "NubankShortener",
      clean: true,
      devices: ["iPhone 16"],
      disable_concurrent_testing: true
    )
  end

end