default_platform(:ios)

platform :ios do

  desc "Run unit tests"

  lane :tests do
    scan(
      scheme: "NubankShortener",
      clean: true,
      devices: ["iPhone 13 Pro Max"],
      disable_concurrent_testing: true
      skip_package_dependencies_resolution: true
    )
  end

end