name: Generate PR Description by AI

on:
  pull_request:
    types: [opened]

jobs:
  ai_description:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: PR Agent Action
        uses: CodiumAI/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_AGENT_CONFIG.default_command: "describe"
