name: iOS Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  tests:

    runs-on: macos-15

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install latest bundler
        run: gem install bundler -v 2.5.22
      
      - name: Install gems
        run: bundle _2.5.22_ install
      
      - name: Run Fastlane Tests
        run: bundle _2.5.22_ exec fastlane tests
